# ~/.config/lazygit/config.yml
os:
  editCommand: 'nvim'
  editCommandTemplate: '{{editor}} +{{line}} {{filename}}'
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --syntax-theme=Visual Studio Dark+
